services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workoutsdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: workouts_app
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

volumes:
  pgdata:
