# Base de datos
spring.datasource.url=${ENTRENASYNC_WORKOUTS_PGSQL_DB_URL}
spring.datasource.username=${ENTRENASYNC_WORKOUTS_PGSQL_DB_USERNAME}
spring.datasource.password=${ENTRENASYNC_WORKOUTS_PGSQL_DB_PASSWORD}

# JPA y SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=never
#dummy

# Logging restringido
logging.level.root=info
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
